class MetadataFields:
    PROCESS_ID = "process_id"
    TIMESTAMP = "timestamp"
    IS_VALID = "is_valid"
    VALIDATION_ISSUES = "validation_issues"
    SOURCE_SYSTEM = "source_system"
    SOURCE_FILE_NAME = "source_file_name"
    INGESTION_TIME = "ingestion_time"

class OtherFields:
    TOTAL_FIXTURES = "total_fixtures"
    FETCHED_COUNT = "fetched_count"
    FETCHED_PERCENTAGE = "fetched_percentage"
    IS_COMPLETE = "is_complete"
    LAST_UPDATED = "last_updated"
    YEAR = "year"
    IS_FETCHED_STAT = "is_fetched_stat"
    FETCH_STAT_TIME = "fetch_stat_time"

class TableNames:
    FIXTURES = "fixtures"
    TEAMS = "teams"
    SILVER_FIXTURE_STATS = "silver_fixture_stats"
    PLAYERS = "players"
    PLAYER_STATS = "player_stats"
    STAGING_LEAGUES = "league_raw_data"
    STAGING_TEAMS = "team_raw_data"
    STAGING_FIXTURE = "fixture_tracking"
    TRACKING_FETCH_FIXTURE_STAT = "tracking_fetch_fixture_stat"
    TRACKING_FETCH_FIXTURE_STAT_LEAGUE = "tracking_fetch_fixture_stat_league"
    BRONZE_TEAMS = "bronze_teams"
    BRONZE_LEAGUES = "bronze_leagues"
    BRONZE_FIXTURES = "bronze_fixtures"
    BRONZE_FIXTURE_STATS = "bronze_fixture_stats"
    SILVER_LEAGUES = "silver_leagues"
    FLATTENED_SILVER_TEAMS = "flattend_silver_teams"
    SILVER_TEAMS = "silver_teams"
    SILVER_FIXTURES = "silver_fixtures"
    FLATTENED_BRONZE_FIXTURES = "flattend_bronze_fixtures"
    LEAGUES = "leagues"
    FIXTURE_STATS = "fixture_stats"
    INTERMEDIATE_SILVER_FIXTURE_STATS = "intermediate_silver_fixture_stats"
    SILVER_FIXTURE_STATS = "silver_fixture_stats"
    DIM_LEAGUES = "dim_leagues"
    DIM_DATES = "dim_dates"
    DIM_TEAMS = "dim_teams"
    DIM_FIXTURES = "dim_fixtures"
    DIM_FIXTURE_STATS = "dim_fixture_stats"
    FACT_MATCH_RESULT = "fact_match_result"
    FACT_MATCH_STATS = "fact_match_stats"
    FACT_MATCH_STATISTICS = "fact_match_statistics"
    FACT_TEAM_RESULT = "fact_team_result"
    FACT_TEAM_MATCH_STATS = "fact_team_match_stats"
    FACT_TEAM_RESULT_SUMMARY = "fact_team_result_summary"

class CommonFields:
    FIXTURE_ID = "fixture_id"
    TEAM_ID = "team_id"
    LEAGUE_ID = "league_id"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    EFFECTIVE_FROM = "effective_from"
    EFFECTIVE_TO = "effective_to"
    IS_CURRENT = "is_current"

class DateFields:
    DATE_KEY = "date_key"
    DATE = "date"
    YEAR = "year"
    MONTH = "month"
    DAY = "day"
    MONTH_NAME = "month_name"
    MONTH_NAME_SHORT = "month_name_short"
    QUARTER = "quarter"
    WEEK_OF_YEAR = "week_of_year"
    DAY_OF_MONTH = "day_of_month"
    DAY_OF_WEEK = "day_of_week"
    DAY_OF_YEAR = "day_of_year"
    IS_WEEKEND = "is_weekend"
    DAY_NAME = "day_name"
    DAY_NAME_SHORT = "day_name_short"
    SEASON = "season"
    MATCH_DAY_CATEGORY = "match_day_category"


class LeagueFields:
    LEAGUE_KEY = "league_key"
    LEAGUE_NAME = "name"
    TYPE = "type"
    COUNTRY = "country"
    LOGO = "logo"
    FLAG = "flag"
    COUNTRY_FLAG = "country_flag"

class TeamFields:
    TEAM_KEY = "team_key"
    TEAM_NAME = "name"
    LOGO = "logo"
    COUNTRY = "country"
    CODE = "code"
    FOUNDED = "founded"
    NATIONAL = "national"
    COUNTRY_FLAG = "country_flag"
    STADIUM_ID = "stadium_id"
    STADIUM_NAME = "stadium_name"
    STADIUM_ADDRESS = "stadium_address"
    CITY = "city"
    CAPACITY = "capacity"
    STADIUM_IMAGE = "stadium_image"
    STADIUM_SURFACE = "stadium_surface"
    TEAM_AGE = "team_age"
    CAPACITY_CATEGORY = "capacity_category"

class FixtureFields:
    FIXTURE_KEY = "fixture_key"
    REFEREE = "referee"
    DATE = "date"
    TIMEZONE = "timezone"
    TIMESTAMP = "timestamp"
    FIRST_PERIOD = "first_period"
    SECOND_PERIOD = "second_period"
    STADIUM_ID = "stadium_id"
    STATUS = "status"
    ELAPSED = "elapsed"
    SEASON = "season"
    ROUND = "round"
    LEAGUE_STANDINGS = "league_standings"
    HOME_TEAM_ID = "home_team_id"
    AWAY_TEAM_ID = "away_team_id"
    GOALS_HOME = "goals_home"
    GOALS_AWAY = "goals_away"
    SCORE_HALFTIME_HOME = "score_halftime_home"
    SCORE_HALFTIME_AWAY = "score_halftime_away"
    SCORE_FULLTIME_HOME = "score_fulltime_home"
    SCORE_FULLTIME_AWAY = "score_fulltime_away"
    SCORE_FULLTIME = "score_fulltime"
    SCORE_HALFTIME = "score_halftime"
    SCORE_EXTRATIME = "score_extratime"
    SCORE_EXTRATIME_HOME = "score_extratime_home"
    SCORE_EXTRATIME_AWAY = "score_extratime_away"
    SCORE_PENALTY_HOME = "score_penalty_home"
    SCORE_PENALTY_AWAY = "score_penalty_away"

class FixtureStatsFields:
    FIXTURE_STAT_KEY = "fixture_stat_key"
    SHOTS_ON_GOAL = "shots_on_goal"
    SHOTS_OFF_GOAL = "shots_off_goal"
    BLOCKED_SHOTS = "blocked_shots"
    SHOTS_INSIDEBOX = "shots_insidebox"
    SHOTS_OUTSIDEBOX = "shots_outsidebox"
    FOULS = "fouls"
    CORNER_KICKS = "corner_kicks"
    OFFSIDES = "offsides"
    BALL_POSSESSION = "ball_possession"
    YELLOW_CARDS = "yellow_cards"
    RED_CARDS = "red_cards"
    GOALKEEPER_SAVES = "goalkeeper_saves"
    TOTAL_PASSES = "total_passes"
    ACCURATE_PASSES = "accurate_passes"
    PASSES_SUCCESS_PERCENTAGE = "passes_success_percentage"
    EXPECTED_GOALS_RATE = "expected_goals_rate"

class DimRefereeFields:
    REFEREE_KEY = "referee_key"
    REFEREE_ID = "referee_id"
    REFEREE_NAME = "name"
    REFEREE_TYPE = "type"
    REFEREE_COUNTRY = "country"
    REFEREE_COUNTRY_FLAG = "country_flag"
    TOTAL_MATCHES = "total_matches"
    TOTAL_YELLOW_CARDS = "total_yellow_cards"
    TOTAL_RED_CARDS = "total_red_cards"
    AVERAGE_YELLOW_CARDS = "average_yellow_cards"
    AVERAGE_RED_CARDS = "average_red_cards"

class FactMatchResultFields:
    MATCH_KEY = "match_key"
    DIM_FIXTURE_KEY = "dim_fixutre_key"
    DIM_FIXTURE_STAT_KEY = "dim_fixture_stat_key"
    DIM_DATE_KEY = "dim_date_key"
    DIM_HOME_TEAM_KEY = "dim_home_team_key"
    DIM_AWAY_TEAM_KEY = "dim_away_team_key"
    DIM_LEAGUE_KEY = "dim_league_key"

    LEAGUE_NAME = "league_name"
    HOME_TEAM_NAME = "home_team_name"
    AWAY_TEAM_NAME = "away_team_name"
    SEASON = "season"
    ROUND = "round"
    MATCH_STATUS = "match_status"
    FIRST_PERIOD = "first_period"
    SECOND_PERIOD = "second_period"
    ELAPSED = "elapsed"

    GOAL_SCORED = "goal_scored"
    GOAL_CONCEDED = "goal_conceded"
    GOALS_HOME = "goals_home"
    GOALS_AWAY = "goals_away"
    SCORE_HALFTIME_HOME = "score_halftime_home"
    SCORE_HALFTIME_AWAY = "score_halftime_away"
    SCORE_FULLTIME_HOME = "score_fulltime_home"
    SCORE_FULLTIME_AWAY = "score_fulltime_away"
    SCORE_EXTRATIME_HOME = "score_extratime_home"
    SCORE_EXTRATIME_AWAY = "score_extratime_away"
    SCORE_PENALTY_HOME = "score_penalty_home"
    SCORE_PENALTY_AWAY = "score_penalty_away"
    
    
    GOAL_DIFF = "goal_diff"
    MATCH_RESULT = "match_result"  # e.g., 'Home Win', 'Away Win', 'Draw'
    IS_DRAW = "is_draw"
    IS_HOME_WIN = "is_home_win"
    IS_AWAY_WIN = "is_away_win"
    IS_LEAGUE_STANDINGS = "is_league_standings"
    WIN = "win"
    LOSE = "lose"
    DRAW = "draw"
    WIN_PERCENTAGE = "win_percentage"
    TEAM_NAME = "team_name"

    # Agg fields
    TOTAL_GOALS_SCORED = "total_goals_scored"
    TOTAL_GOALS_CONCEDED = "total_goals_conceded"
    TOTAL_GOALS = "total_goals"
    TOTAL_WIN = "total_win"
    TOTAL_LOSE = "total_lose"
    TOTAL_DRAW = "total_draw"
    MATCH_PLAYED = "match_played"
    COMPETITION = "competition"

class FactMatchStatisticFields:
    MATCH_STATISTIC_KEY = "match_statistic_key"
    DIM_FIXTURE_KEY = "dim_fixture_key"
    DIM_FIXTURE_STAT_KEY = "dim_fixture_stat_key"
    DIM_DATE_KEY = "dim_date_key"
    DIM_TEAM_KEY = "dim_team_key"
    DIM_LEAGUE_KEY = "dim_league_key"

    FIXTURE_ID = "fixture_id"
    TEAM_ID = "team_id"
    LEAGUE_NAME = "league_name"
    TEAM_NAME = "team_name"
    SEASON = "season"
    ROUND = "round"
    IS_LEAGUE_STANDINGS = "is_league_standings"
    MATCH_RESULT = "match_result"
    MATCH_STATUS = "match_status"
    FIRST_PERIOD = "first_period"
    SECOND_PERIOD = "second_period"
    ELAPSED = "elapsed"
    
    GOALS_SCORED = "goals_scored"
    GOALS_CONCEDED = "goals_conceded"
    GOALS_SCORED_FIRST_HALF = "goals_scored_first_half"
    GOALS_CONCEDED_FIRST_HALF = "goals_conceded_first_half"
    GOALS_SCORED_SECOND_HALF = "goals_scored_second_half"
    GOALS_CONCEDED_SECOND_HALF = "goals_conceded_second_half"
    GOALS_SCORED_EXTRATIME = "goals_scored_extratime"
    GOALS_CONCEDED_EXTRATIME = "goals_conceded_extratime"
    GOALS_SCORED_PENALTY = "goals_scored_penalty"
    GOALS_CONCEDED_PENALTY = "goals_conceded_penalty"

    SHOTS_ON_GOAL = "shots_on_goal"
    SHOTS_OFF_GOAL = "shots_off_goal"
    BLOCKED_SHOTS = "blocked_shots"
    SHOTS_INSIDEBOX = "shots_insidebox"
    SHOTS_OUTSIDEBOX = "shots_outsidebox"
    FOULS = "fouls"
    CORNER_KICKS = "corner_kicks"
    OFFSIDES = "offsides"
    BALL_POSSESSION = "ball_possession"
    YELLOW_CARDS = "yellow_cards"
    RED_CARDS = "red_cards"
    GOALKEEPER_SAVES = "goalkeeper_saves"
    TOTAL_PASSES = "total_passes"
    ACCURATE_PASSES = "accurate_passes"
    PASSES_SUCCESS_PERCENTAGE = "passes_success_percentage"
    EXPECTED_GOALS_RATE = "expected_goals_rate" 

class FactTeamMatchStatsFields:
    FACT_KEY = "fact_key"
    MATCH_PLAYED = "match_played"
    # Goal summary fields
    TOTAL_GOALS_SCORED = "total_goal_scored"
    AVG_GOALS_SCORED = "avg_goals_scored"
    TOTAL_GOALS_CONCEDED = "total_goals_conceded"
    AVG_GOALS_CONCEDED = "avg_goals_conceded"
    TOTAL_GOALS_FIRSTHALF = "total_goals_firsthalf"
    TOTAL_GOALS_SECONDHALF = "total_goals_secondhalf"
    SCORE_FIRST_HALF_PERCENTAGE = "score_firsthalf_percentage"
    SCORE_SECOND_HALF_PERCENTAGE = "score_secondhalf_percentage"
    CONCED_FIRST_HALF_PERCENTAGE = "conceded_firsthalf_percentage"
    CONCED_SECOND_HALF_PERCENTAGE = "conceded_secondhalf_percentage"
    
    # Stats summary fields
    TOTAL_SHOTS_ON_GOAL = "total_shots_on_goal"
    AVG_SHOTS_ON_GOAL = "avg_shots_on_goal"
    TOTAL_SHOTS_OFF_GOAL = "total_shots_off_goal"
    TOTAL_BLOCKED_SHOTS = "total_blocked_shots"
    TOTAL_BLOCKED_SHOTS = "total_blocked_shots"
    TOTAL_SHOTS_INSIDEBOX = "total_shots_insidebox"
    AVG_SHOTS_INSIDEBOX = "avg_shots_insidebox"
    TOTAL_SHOTS_OUTSIDEBOX = "total_shots_outsidebox"
    AVG_SHOTS_OUTSIDEBOX = "avg_shots_outsidebox"
    TOTAL_GOALKEEPER_SAVES = "total_goalkeeper_saves"
    TOTAL_FOULS = "total_fouls"
    AVG_FOULS = "avg_fouls"
    TOTAL_CORNER_KICKS = "total_corner_kicks"
    AVG_CORNER_KICKS = "avg_corner_kicks"
    TOTAL_OFFSIDES = "total_offsides"
    TOTAL_YELLOW_CARDS = "total_yellow_cards"
    AVG_YELLOW_CARDS = "avg_yellow_cards"
    TOTAL_RED_CARDS = "total_red_cards"
    AVG_RED_CARDS = "avg_red_cards"
    AVG_BALL_POSSSESSION = "avg_ball_possession"
    TOTAL_PASSES = "total_passes"
    TOTAL_ACCURATE_PASSES = "total_accurate_passes"
    AVG_PASS_SUCCESS_PERCENTAGE = "avg_pass_success_percentage"
    AVG_EXPECTED_GOALS_RATE = "avg_expected_goals_rate"



